// This file is auto-generated by gen_irreps.cc, don't modify
#include <openssl/bn.h>
#include <iostream>
#include <cstdlib>
#include <vector>
using namespace std;
void set_irrep(vector<int> &p, unsigned n) {
switch (n) {
case 8192: {
p.push_back(8192);
p.push_back(9);
p.push_back(5);
p.push_back(2);
p.push_back(0);
} break;
case 16382: {
p.push_back(16382);
p.push_back(3393);
p.push_back(0);
} break;
default:
 cerr << "Internal error: n out of bounds!";
 exit(-1);
}
}
